Update to v0.5.9-beta1 + update components
flathub/net.lutris.Lutris pull request #159
Opened 2021-08-01 18:03 UTC by FakeShemp

2021-08-01 20:22 UTC, A6GibKm requested changes

2021-08-01 20:22 UTC, A6GibKm commented on net.lutris.Lutris.yml
> +        url: "https://github.com/lutris/lutris/archive/refs/tags/v0.5.9-beta1.tar.gz"
Use https://github.com/lutris/lutris/archive/v0.5.9-beta1.tar.gz please.

2021-08-01 20:22 UTC, A6GibKm commented
This could be split into two commits, one for the modules and one only updating lutris. If the first one builds we can merge it asap.

2021-08-06 16:03 UTC, FakeShemp commented
bot, build

2021-08-06 21:01 UTC, FakeShemp commented
bot, build

2021-10-12 13:25 UTC, A6GibKm commented
I am getting an error 

    2021-10-12 15:25:11,376: No file /tmp/lutris-1db86942-b5ce-456b-9717-4fc39e57a8b0

2021-11-16 18:18 UTC, FakeShemp commented
bot, build

2021-11-21 17:44 UTC, Unrud commented
See #194

2021-11-21 19:19 UTC, A6GibKm commented
Closed in favor of https://github.com/flathub/net.lutris.Lutris/pull/193. Thanks!

2021-11-21 19:19 UTC, closed without merging